---

- block:

  - name: Upgrade all packages
    ansible.builtin.yum:
      name: "*"
      state: latest

  - name: Enable EPEL
    ansible.builtin.yum:
      name: epel-release
      state: latest

  - name: Install required packages
    ansible.builtin.yum:
      name: "{{ software }}"
      state: latest

  - name: Remove unneeded packages
    ansible.builtin.yum:
      autoremove: yes


  become: yes
  become_user: root
  tags:
    - software