---

- name: Activate google-authentictor PAM module
  pamd:
    name: sshd
    type: auth
    control: required
    module_path: pam_sepermit.so
    new_type: auth
    new_control: required
    new_module_path: pam_google_authenticator.so
    state: before
  become: yes
  become_user: root