---

- include_tasks: secrets.yml
  tags: secrets

- include_tasks: systemd.yml
  tags: config

- set_fact:
   vpninfo: "{{vpn.site_to_site}}"

- name: Configure site to site VPNs
  include_tasks: config-site2site.yml
  vars:
    name: "{{ item.key }}"
    vpn: "{{ item.value }}"
  loop: "{{ vpninfo | dict2items }}"
  tags: config
