---

# - name: Local keys directory
#   file:
#     state: directory
#     path: "{{local_keys_dir}}"
#     mode: "0750"
#   delegate_to: localhost
#   run_once: yes

# - set_fact:
#    vpninfo: "{{vpn.site_to_site}}"

# - name: Manage VPN shared secrets
#   include_tasks: secret.yml
#   vars:
#     name: "{{ s2svpn.key }}"
#     vpn: "{{ s2svpn.value }}"
#   loop: "{{ vpninfo | dict2items }}"
#   loop_control:
#     loop_var: s2svpn